/**
 * Predefined skills database for resume matching.
 * Used for case-insensitive keyword extraction.
 */
export const SKILLS_DATABASE = [
  // Programming languages
  'JavaScript',
  'TypeScript',
  'Python',
  'Java',
  'C#',
  'C++',
  'Ruby',
  'Go',
  'Rust',
  'PHP',
  'Swift',
  'Kotlin',
  'Scala',
  'R',
  'SQL',
  'HTML',
  'CSS',
  // Frameworks & libraries
  'React',
  'Angular',
  'Vue.js',
  'Node.js',
  'Express',
  'Django',
  'Flask',
  'Spring Boot',
  'Ruby on Rails',
  '.NET',
  'jQuery',
  'Bootstrap',
  'Tailwind CSS',
  'Next.js',
  'Nuxt.js',
  'Svelte',
  // Databases
  'MongoDB',
  'PostgreSQL',
  'MySQL',
  'Redis',
  'Elasticsearch',
  'Firebase',
  'DynamoDB',
  // DevOps & cloud
  'Docker',
  'Kubernetes',
  'AWS',
  'Azure',
  'GCP',
  'CI/CD',
  'Git',
  'Jenkins',
  'Terraform',
  'Linux',
  'REST API',
  'GraphQL',
  // Tools & practices
  'Agile',
  'Scrum',
  'Jira',
  'GitHub',
  'GitLab',
  'Figma',
  'Postman',
  'Unit Testing',
  'Machine Learning',
  'Data Analysis',
  'Data Visualization',
  'Tableau',
  'Power BI',
  'Excel',
  // Soft skills
  'Leadership',
  'Communication',
  'Problem Solving',
  'Team Collaboration',
  'Project Management',
  'Technical Writing',
  'Mentoring',
];
